
title: Valensas << Technology Services
description: >- # this means to ignore newlines until "baseurl:"
  Founded in 2005, Valensas is a Turkey based information technology solution provider,
  helping customers with focused attention and intelligent know-how.
  As the company has expanded, we have developed a unique series of innovative
  products and services that are exclusive to Valensas to meet and exceed our clients needs.
  We create applications and integrate services that ensure our customers remain on the
  cutting edge of technology and offer them in conjunction with our digital business services.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
host: 0.0.0.0
# port: 4000

nav:
  - text: Portfolio
    link: /portfolio/
  - text: Enterprise Solutions
    link: /enterprise-solutions/
  - text: Projects
    link: /projects/
  - text: Contact
    link: /contact/

footer_content_1: 8,750,000+ users registered since 2008
footer_content_2: We create products that help your life to look even better.
footer_socials_title: Follow
footer_socials:
  - text: Linkedin
    link: https://www.linkedin.com/company/valensas/
  - text: Twitter
    link: https://twitter.com/valensascom
  - text: Youtube
    link: https://www.youtube.com/user/ValensasTechnology

collections:
  projects:
    output: true

application_form_cta: Let's work together
application_form_cta_link: https://forms.gle/s2CpNARVn8nth7GW7

contact_form_cta: Keep in touch with us
contact_form_cta_link: https://forms.gle/whcxhqkurJQL6hh18

google_maps_url: https://maps.google.com/maps?q=valensas+re%C5%9Fitpa%C5%9Fa&t=&z=11&ie=UTF8&iwloc=&output=embed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

kramdown:
  hard_wrap: true

include: [".well-known"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
